services:
  - type: web
    name: mutual-fund-recommender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Myproject.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Myproject.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: EMAIL_USE_SSL
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_HOST
        sync: false
    postDeploy:
      commands:
        - python manage.py migrate
        - python manage.py collectstatic --noinput
