# Generated by Django 5.2 on 2025-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RenameField(
            model_name='mutualfund',
            old_name='category',
            new_name='fund_name',
        ),
        migrations.RenameField(
            model_name='mutualfund',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='mutualfund',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='mutualfund',
            name='profit_type',
        ),
        migrations.RemoveField(
            model_name='mutualfund',
            name='return_rate',
        ),
        migrations.RemoveField(
            model_name='mutualfund',
            name='risk',
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='investment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
