# Generated by Django 5.2 on 2025-05-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_delete_task_rename_category_mutualfund_fund_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(blank=True, max_length=300, null=True, unique=True)),
            ],
        ),
    ]
