# Generated by Django 5.2 on 2025-05-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_allmutualfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='nav',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
