# Generated by Django 5.2 on 2025-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_mutualfund_nav_mutualfund_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='return_1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
