# Generated by Django 5.2 on 2025-05-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_mutualfund_return_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfund',
            name='return_1',
        ),
    ]
