# Generated by Django 5.2 on 2025-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_remove_mutualfund_return_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfund',
            name='rating',
            field=models.CharField(blank=True, null=True),
        ),
    ]
